// react/timesheet-app/src/components/AppShell.jsx
import { NavLink, useNavigate } from 'react-router-dom';
import { PAGES } from '../data/mockData';

export default function AppShell({ children }) {
  const navigate = useNavigate();

  return (
    <>
      <div className="topbar">
        <div className="logo">TS</div>
        <div>
          <div className="product">Timesheet Management System</div>
          <div className="sub">Internal Staff Portal</div>
        </div>
        <div className="spacer" />
        <span className="pill">DD/MM/YYYY</span>
        <div className="avatar">
          <div className="dot">CW</div>
          <div>Chris Wong ▼</div>
        </div>
      </div>
      <div className="layout">
        <aside className="side">
          <div className="nav-title">Main Menu</div>
          <nav className="nav">
            {PAGES.map((p) => (
              <NavLink
                key={p.id}
                to={`/${p.id}`}
                className={({ isActive }) => isActive ? 'active' : ''}
              >
                <span className="icon">{p.icon}</span>
                {p.label}
              </NavLink>
            ))}
          </nav>
        </aside>
        <main className="main-content">{children}</main>
      </div>
    </>
  );
}

// timesheet-vue/src/components/AppShell.vue
<template>
  <div>
    <!-- Topbar -->
    <div class="topbar">
      <div class="logo">TS</div>
      <div>
        <div class="product">Timesheet Management System</div>
        <div class="sub">Internal Staff Portal</div>
      </div>
      <div class="spacer" />
      <span class="pill">DD/MM/YYYY</span>
      <div class="avatar">
        <div class="dot">CW</div>
        <div>Chris Wong ▼</div>
      </div>
    </div>

    <!-- Layout -->
    <div class="layout">
      <aside class="side">
        <div class="nav-title">Main Menu</div>
        <nav class="nav">
          <RouterLink
            v-for="p in PAGES"
            :key="p.id"
            :to="`/${p.id}`"
          >
            <span class="icon">{{ p.icon }}</span>
            {{ p.label }}
          </RouterLink>
        </nav>
      </aside>
      <main class="main-content">
        <slot />
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { PAGES } from '@/data/mockData'
</script>
